#! /usr/bin/env bash
#
#                        (((((((/                                     
#                     /(((((((/                                       
#                   ((((((((   /                                      
#                /(((((((/  .///                                      
#              ((((((((   //////                                      
#           /(((((((*  ,////////                                      
#         /(((((((   ///////////                                      
#                 ./////////////                                      
#                .//////////////                                      
#                .//////////////                                      
#                .//////////////                                      
#                .//////////////                                      
#                .//////////////                                      
#                .//////////////                                      
#                .//////////////                                      
#                .//////////////                                      
#                .//////////////                                      
#                .//////////////                                      
#                .//////////////                                      
#                .//////////////                                      
#                .///////////.                                        
#               /////////.      ,///////////////////////////////      
#             ///////       *////////////////////////////////*        
#           *///*       ///////////////////////////////////.          
#         ,/*       /////////////////////////////////////             
#              ,//////////////////////////////////////.               
#         /////////////////////////////////////////                  
#
# DESC: Arch Linux post installation script that will install and configure window manager along with all applications and utilities that are needed to create fully functional desktop environment.
# WARNING: Run this script at your own risk.

source "./scripts/output.sh"
source "./scripts/addrepos.sh"
source "./scripts/audioserver.sh"
source "./scripts/configfiles.sh"
source "./scripts/resources.sh"
source "./scripts/startup.sh"
source "./scripts/dynamictheme.sh"

dynamic_theme=false

msg "LimOS is a post installation script that will install and configure window manager along with all applications and utilities that are needed to create fully functional desktop environment. This script should work on any Arch Linux distro. You run this script at your own risk!"

yn "About dynamic theme: it's a script that will change desktop theme and wallpaper every two hours. You can see all themes here: https://gitlab.com/Limak01/dotfiles/-/tree/master/.screenshots If you disable dynamic theme by default theme number 6 will be used. \n\nDo you want to enable dynamic theme?" && dynamic_theme=true 

addrepos || error "Adding repositories"
audioserver || error "Adding audioserver"

sudo pacman -Sy --noconfirm --needed - < pkglist.txt || error "Installing essential packages"

getresources || error "Getting resources"

configfiles || error "Copying config files"

if ! $dynamic_theme; then
    apply_default_theme || error "Applying default theme"  
else
    enable_dynamic_theme || error "Enabling dynamic theme"
fi

startupstuff || error "Configuring system startup stuff"

yn "LimOS is installed do you want to reboot?" && reboot
