#! /usr/bin/env bash
#                                                                      
#                                                                      
#                                        .......                       
#                              ..,;cllodxkkOOOkkxdolc;,,:oxxo:.        
#                          .,cdk0KXNNNXXXXXXXXXXXXXNXXXXXXXXXXo.       
#                      .'cdOXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXd.       
#                    .cxKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNO'        
#                  'o0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx.        
#                'oKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXN0;        
#              .c0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo.       
#             .dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNk.       
#            ,kXXXXXKOOXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNO'       
#           ,OXXXXXk;..dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXN0,       
#          'kXXXXXx. .:0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNO'       
#         .dXXXXXx. .lKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNk.       
#         :KXXXNO, .cKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXl.       
#        .xXXXXXl  ,0NXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXN0,        
#        ,0NXXNO, .oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo.        
#        cKNXXNk. .xNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXk.         
#        lXXXXNx. .xNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO,          
#        lXXXXN0c':0NXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO;           
#        cXXXXXXXKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXk,            
#        ;0NXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKd.             
#        .xNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXk;.              
#         cKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXOc.                
#         ;0NXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKx:.                  
#        .xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKkl'.                    
#        ;0NXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXKko:'.                       
#        .l0XXX0kxxk0KXXXXNNXXXXXXK0OOxoc;'.                           
#          .,;,..  ..',;::cccc::;,'...                                 
#                                                                      
# DESC: Arch Linux post installation script that will install and configure window manager along with all applications and utilities that are needed to create fully functional desktop environment.
# WARNING: Run this script at your own risk.

GTK_THEME="Fluent-green-Dark"
ICON_THEME="Fluent-green-dark"
QT_THEME="Fluent-green-dark"

GTK_CONFIG_PATH="$HOME/.config/gtk-3.0"

source "./src/output.sh"
source "./src/repos.sh"
source "./src/config.sh"
source "./src/packages.sh"
source "./src/startup.sh"

msg "LimOS is a post installation script that will install and configure window manager along with all applications and utilities that are needed to create fully functional desktop environment. This script should work on any Arch Linux distro. You run this script at your own risk!"

addrepos || error "Adding repositories"
install_packages || error "Installing essential packages"
configure_desktop || error "Copying config files"
startup || error "Configuring system startup programs"

yn "LimOS is installed do you want to reboot?" && reboot
